packages:
  - "packages/*"

catalog:
  eslint: "^10.10.0"
  oxlint: "^1.83.0"
  oxlint-tsgolint: "^7.0.2001"

overrides:
  # nuxt@4.5.2
  glob: "^13.0.0"

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  unrs-resolver: true
