packages:
  - "packages/*"

catalog:
  eslint: ^10.11.0
  oxlint: ^1.86.0
  oxlint-tsgolint: ^7.0.2003
  typescript: ~6.0.3
  vue-tsc: ^3.3.12

overrides:
  # nuxt@4.5.2
  glob: "^13.0.0"

allowBuilds:
  '@parcel/watcher': true
  '@prisma/engines': true
  esbuild: true
  prisma: true
  unrs-resolver: true
  vue-demi: false
  workerd: true
